apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-default-storageclass
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/nfs
parameters:
  path: /kubs/sc001
  server: 192.168.80.16

