apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-pv2
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /recordings
    server: 192.168.80.16  # Replace with your NFS server IP

